### ISSUE TITLE
Listenery

### ISSUE THREAD

**Issue by kowalczyk-mateusz** [reueck/sosnowietz_zdroj#1]
https://github.com/reueck/sosnowietz_zdroj/blob/2d39806f7f01c3afc3002db49f5bd4f7a82a4d25/js/script.js#L8

Po każdym kliknięciu w nawigacje przechodzisz forEachem po linkach i dodajesz listener, przez co po kilku klikach dany element bedzie miał kilka listenerów. Wyciągnij tę funkcję poza navHandler lub usuwaj te listenery

**Comment by reueck** [comment]
Rozwiązane
